language: node_js
node_js:
  - '8'
script:
  - npm run test

before_script:
  - npm run bootstrap

after_success:
  - npm run codecov"
cache:
  directories:
    - ./node_modules
    - ./packages/*/node_modules