language: node_js
node_js:
  - '10'
script:
  - yarn test

before_script:
  - yarn bootstrap

after_success:
  - yarn codecov"
cache:
  directories:
    - ./node_modules
    - ./packages/*/node_modules